### ISSUE TITLE
Enforce use of `use_frameworks!`

### ISSUE THREAD

**Issue by neonichu** [neonichu/Rome#14]
Either complain when it isn't there or do #2

Currently, the `mv` will just fail.

**Comment by segiddins** [comment]
Can you a pre-install hook to get `Config.instance.podfile` and add it?

**Comment by segiddins** [comment]
(My vision for the new podfile will address this, btw, by making the integration strategy configurable, and the `Rome` integration strategy would be able to use the `Pods project` strategy internally)

**Comment by neonichu** [comment]
Yah, I think there's some things to consider (see #15) before this can become an actual built-in installation strategy. It is still quite fragile :)

**Comment by segiddins** [comment]
@neonichu sure, but we've got some time :)
