### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by neonichu** [neonichu/Rome#2]
Currently, there's way too much boilerplate in the Podfile, it should just be

```ruby
pod 'Alamofire'
```

also the command is kinda longish. So ideally, one would do something like:

```bash
$ pod bootstrap
```

and that would amend the Podfile for consumption by the actual `pod install` and also pass the extra arguments to it.

**Comment by neonichu** [comment]
Maybe the platform needs to be specified? Would be kinda annoying to first go through all required specs to find out the common denominator of platforms.  ¯\_(ツ)_/¯

**Comment by AliSoftware** [comment]
Couldn't it be possible to add a `pod rome` command that internally calls the same ruby code as `pod install --no-integrate` would do… but tweaking the in-memory ruby representation of the Podfile to add/simulate that `use_framework!` flag internally?
_(Just a thought, didn't check if that's actually possible given CP code architecture)_

**Comment by segiddins** [comment]
That's totally possible @AliSoftware
