### ISSUE TITLE
"Unknown configuration whitelisted"

### ISSUE THREAD

**Issue by michaeleiselsc** [neonichu/Rome#23]
I get the following error when trying to build with cocoapods-rome using Cocoapods 0.35.0 (which can't be updated, so no worries if you can't figure it out), when I run `pod install`:

$ pod install
Updating local specs repositories
Analyzing dependencies
[!] Unknown configuration whitelisted: uiautomation.`

Any ideas what might be causing the issue?

**Comment by segiddins** [comment]
Rome requires CocoaPods 0.38.

**Comment by neonichu** [comment]
Indeed, I believe it would break because of the plugin API alone.
