### ISSUE TITLE
Not able to install Taylor framework - What i am doing wrong ?

### ISSUE THREAD

**Issue by karthikprabhuA** [neonichu/Rome#26]
Installing Taylor framework fails and giv ing the following error "fatal: repository 'https://github.com/nypisces/Taylor.git/' not found"

PodFile
---Start----
platform :osx, '10.9'
platform :ios, '8.0'
plugin 'cocoapods-rome'

pod 'Taylor'

--End--

 
pod install
Updating local specs repositories

CocoaPods 0.39.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing AFNetworking (1.3.4)
Installing ISO8601DateFormatterValueTransformer (0.6.1)
Installing RKValueTransformers (1.1.2)
Installing RestKit (0.25.0)
Installing SOCKit (1.1)
Installing Taylor (0.1.0)

[!] Error installing Taylor
[!] /usr/bin/git clone https://github.com/nypisces/Taylor.git /var/folders/zx/xkz4mnmj58s52gct0mc2hzbh0000gn/T/d20150909-18579-g54bgr --single-branch --depth 1 --branch 0.1.0

Cloning into '/var/folders/zx/xkz4mnmj58s52gct0mc2hzbh0000gn/T/d20150909-18579-g54bgr'...
remote: Repository not found.
fatal: repository 'https://github.com/nypisces/Taylor.git/' not found

**Comment by segiddins** [comment]
This isn't an issue with Rome -- the source for pods needs to be available in order to download them.
