### ISSUE TITLE
Any chance you could make use of xcpretty to make xcodebuild output more sane?

### ISSUE THREAD

**Issue by ExoticObjects** [neonichu/Rome#34]
https://github.com/supermarin/xcpretty

Using Rome results in the generation of, I'm guessing, 50k lines of output. That's about as useful as zero lines out output. Apple thinks that's a good idea, but you could make the output more useful in Rome!

**Comment by segiddins** [comment]
@ExoticObjects I think a PR  might be appreciated by @neonichu

**Comment by neonichu** [comment]
I'm a bit reluctant to do that as the full output is only shown in case of build errors and `xcpretty` would possibly mask information that is needed to debug them.

**Comment by ExoticObjects** [comment]
@neonichu - if you look on the xcpretty page under 'Raw xcodebuild output' it shows a way to handle that issue. 
@segiddins - I'd love to submit a pull request. But I don't know how to run Rome locally so that I can work on it. All I know how to do with a cocoapods plugin like Rome is what your readme tells me: `plugin 'cocoapods-rome.'` [This guide](https://guides.cocoapods.org/contributing/contribute-to-cocoapods.html) is helpful, but doesn't tell me quite what I need to know...

**Comment by neonichu** [comment]
@ExoticObjects that would still make Rome harder to use in my opinion, now you have two places to look for an error. I feel like `xcpretty` is a good tool for cases where you want to look at the output in the good case most times, but not so much as an error log.
