### ISSUE TITLE
Question: How is Cocoapods Rome different than Cocoapods-Packager?

### ISSUE THREAD

**Issue by ExoticObjects** [neonichu/Rome#36]
They are clearly related. [Cocoapods-packager](https://github.com/CocoaPods/cocoapods-packager) can  also create dynamic libraries. 

What are the specific differences and reasons to use one instead of the other?

**Comment by neonichu** [comment]
The idea of the packager is to create a single binary, which vendors all its dependencies, so that people can offer a compiled version of their Pod. In contrast to that, Rome builds each Pod individually for manual integration into your own project.

**Comment by matynz** [comment]
Sorry for waking up an old issue. 

@neonichu 
I'm using cocoapods with use_frameworks activates(we use swift)
But could I use rome to wrap all pods, which my project depends on but can't install with cocoapods because of transitive dependencies that include static binaries, in a dinamyc framework?
