### ISSUE TITLE
symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by absolutlabs** [neonichu/Rome#41]
Hello

I read that there were several similar issues since last year but as I understand they are fixed &  closed now. I think I'm missing something obvious, but I can't figure it out. :/

Here is my podfile :
```
platform :ios, '8.0'

plugin 'cocoapods-rome'

source 'https://github.com/CocoaPods/Specs.git'

target 'ALF' do
    pod 'AFNetworking'
end
```

The framework is built with ```pod install```, I import it in my project, but then I can only launch it  on the simulator.
When trying to run it on the iPhone I got the errors
```
ld: warning: ignoring file /Users/vincent/XCode/ALF/Rome/AFNetworking.framework/AFNetworking, missing required architecture arm64 in file /Users/vincent/XCode/ALF/Rome/AFNetworking.framework/AFNetworking (2 slices)

ld: symbol(s) not found for architecture arm64
```

I'm using ```cocoapods-rome-0.5.0```

Thanks for your help

**Comment by neonichu** [comment]
Thanks for reporting, I shipped a new release which fixes this. For simplicity's sake, it requires CocoaPods 1.1.0, though, which is currently in beta.

**Comment by absolutlabs** [comment]
it works great ! thank you :)
