### ISSUE TITLE
Device architectures are missing for some pods

### ISSUE THREAD

**Issue by absolutlabs** [neonichu/Rome#43]
Hello

With the last fix ( #42 ) simulator & device architectures are correctly built into one framework for most of the pods I tried, but I only get simulator ones for few of them.
For example, with  [Underscore.m](https://github.com/robb/Underscore.m) or  [UINavigationItem-Loading](https://github.com/Just-/UINavigationItem-Loading)

Are the pods "invalid" in some way ?

thank you !

**Comment by neonichu** [comment]
Might be that the build path isn't correctly determined because the names aren't C99 identifiers — I'll investigate!

**Comment by neonichu** [comment]
The issue was as expected, the path to the binaries for `lipo` was incorrect, depending on the pod's name. Fixed and shipped in version 0.7.0

**Comment by absolutlabs** [comment]
works perfectly ! 
thank you :)

**Comment by danielmhanover** [comment]
Is this issue fixed in the CP-1.1.0 branch?
