### ISSUE TITLE
iOS frameworks should contain ARM slices

### ISSUE THREAD

**Issue by robb** [neonichu/Rome#8]
When building a framework for iOS, for example AFNetworking:

```ruby
platform :ios, '8.0'
use_frameworks!

plugin 'cocoapods-rome'

pod 'AFNetworking'
```

Rome should also build slices for ARM CPUs. Currently the resulting framework only contains `i386` and `x86_64` slices:

```sh
$ lipo -info Rome/AFNetworking.framework/AFNetworking
Architectures in the fat file: Rome/AFNetworking.framework/AFNetworking are: i386 x86_64
```

**Comment by neonichu** [comment]
Yep, that would make sense - this is basically what #1 is meant to do.

**Comment by hwaxxer** [comment]
I'm still seeing this issue with 0.2.0.

**Comment by hwaxxer** [comment]
#25 fixes this issue.

**Comment by hwaxxer** [comment]
Looks like some frameworks (`AFNetworking`, `Alamofire`, `DateTools`) are placed outside of the `Configuration-sdk` folder.

**Comment by neonichu** [comment]
Ah, I see what the problem is now, target deduplication in newer versions of CP. Would probably make sense to just disable it for Rome. I'll look into it later today.

**Comment by hwaxxer** [comment]
Oh makes sense now. I couldn't figure out why they were disappearing. Thanks!
