### ISSUE TITLE
Build universal binaries

### ISSUE THREAD

**Issue by brennanMKE** [neonichu/Rome#9]
I created a shell script which could be used as a reference to incorporate this functionality into the Ruby plugin. (see link below) It simply uses the -sdk switch for xcodebuild to build for simulator and device then it uses lipo to combine them. I do not know Ruby so I provided as much as I could to make it easy to take it from here.

https://github.com/brennanMKE/BuiltInADay

### 3 Steps

 1. build for simulator (Release-iphonesimulator)
 2. build for device (Release-iphoneos)
 3. combine with lipo

The script I did create does make it possible to simply run `pod -no-integrate` to create the Pods and then the `build_universal.sh` script to create the universal framework in the Rome folder.

You can use `lipo -info <filename>` to get a list of the the architectures.

**Comment by brennanMKE** [comment]
cc @neonichu

**Comment by neonichu** [comment]
Closed by 1809d27939f61d99bc949de93773dff8fecae713
